language: ruby
rvm:
  - "1.9.2"
  - "1.9.3"
  - jruby-19mode # JRuby in 1.9 mode
  - rbx-19mode
branches:
  only:
    - master
before_install: 
  - git submodule update --init --recursive
script: bundle exec rspec spec
